### ISSUE TITLE
Subdirectory convention

### ISSUE THREAD

**Issue by The-42** [tpummer/gm-revorix#3]
This may actually be more of a question... How exactly are subdirectories to be named if someone were to add new scripts? The current `entwicklung` subdir seems a bit generic. I get they're needed because of things like changelogs, but shouldn't those be better integrated in a metadata block into the related script itself? That way we could use subdirs as mere topics and add multiple scripts without having to deal with conflicting changelog / readme / whatever files.

**Comment by fmarczew** [comment]
We should name the subdirs like the script, following the convention like Revorix_Name_Of_The_Script ?
You can have a Readme.md in each subdir i think.

**Comment by tpummer** [comment]
after a short chat: directories are used as collections now, readme files are not necessary
